# Generated by Django 4.2.2 on 2023-06-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transactions',
            field=models.ManyToManyField(blank=True, default=None, related_name='transactions', to='billing.transactionmodel', verbose_name='Транзакции пользователя'),
        ),
    ]
